#!/usr/bin/env bash
# ip-leak-scan.sh — scan OUR plugin for (a) generic copyright/attribution leaks and
#                   (b) the reference's reserved identifiers.
# Usage: ip-leak-scan.sh <our-plugin-path> [reserved-identifiers.txt] [reference-path]
# Findings are LEADS, not verdicts. Triage each 🟢/🟡/🔴 per references/leak-signals.md.
#
# Engineering risk-reduction, NOT legal advice.
set -uo pipefail

TARGET="${1:?usage: ip-leak-scan.sh <our-plugin-path> [reserved-identifiers.txt] [reference-path]}"
RESERVED="${2:-}"
REF="${3:-}"

if [[ ! -e "$TARGET" ]]; then
  echo "ERROR: target '$TARGET' not found" >&2; exit 1
fi

if command -v rg >/dev/null 2>&1; then
  SEARCH()  { rg -n --no-heading -i -e "$1" "$TARGET" 2>/dev/null; }
  SEARCHF() { rg -n --no-heading -F -- "$1" "$TARGET" 2>/dev/null; }
else
  SEARCH()  { grep -rniE "$1" "$TARGET" 2>/dev/null; }
  SEARCHF() { grep -rnF -- "$1" "$TARGET" 2>/dev/null; }
fi

section() {
  local title="$1" pattern="$2"
  local hits; hits="$(SEARCH "$pattern")"
  echo "## $title"
  [[ -n "$hits" ]] && echo "$hits" || echo "  (none)"
  echo
}

echo "============================================================"
echo " IP CLEAN-ROOM LEAK SCAN — target: $TARGET"
[[ -n "$REF" ]] && echo " reference: $REF"
echo " note: leads, not verdicts. Triage with the AFC test + leak-signals.md."
echo "============================================================"
echo

echo "### A. Provenance / attribution leaks (often 🟢 if our expression is original)"
echo
section "License headers & SPDX tags" \
  'SPDX-License-Identifier|GNU (Lesser |Affero )?General Public License|Licensed under the Apache|Mozilla Public License|Permission is hereby granted|Redistribution and use|Copyright \(c\)|\(C\) 20[0-9]{2}|All rights reserved'
section "Copyleft license mentions (escalate to 🔴 if on used code)" \
  'GPL-[23]|AGPL|LGPL|GPLv[23]|MPL-2|copyleft'
section "Author identity" \
  '@author|Authored-by|Signed-off-by|Co-authored-by|[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'
section "Original-repo references" \
  'github\.com/|gitlab\.com/|bitbucket\.org/|Ported from|Adapted from|Based on|Originally (from|written)|taken from|borrowed from'
section "Source-tracking comments" \
  '(TODO|FIXME|HACK|XXX).*(original|upstream|their|port|copied|see )'
section "AI-inserted attribution tells" \
  'generated by|written by (Chat)?GPT|as an AI|courtesy of|source: http'

# --- Reference reserved-identifier matches (the WP-specific danger) ---
echo "### B. Reference identifiers found in OUR code (🔴 — must be removed/reimplemented)"
echo
if [[ -n "$RESERVED" && -f "$RESERVED" ]]; then
  TOKENS="$(grep -vE '^\s*(#|$)' "$RESERVED" | grep -oE '[A-Za-z0-9_][A-Za-z0-9_/-]{3,}' | sort -u)"
  HITS=0
  while IFS= read -r tok; do
    [[ -z "$tok" ]] && continue
    found="$(SEARCHF "$tok")"
    if [[ -n "$found" ]]; then echo "  ⚠️  '$tok':"; echo "$found" | sed 's/^/      /'; HITS=$((HITS+1)); fi
  done <<< "$TOKENS"
  [[ "$HITS" -eq 0 ]] && echo "  ✅ none of the reference's reserved identifiers appear in our code"
else
  echo "  (no reserved-identifiers.txt supplied — run ip-intake-scan.sh first to generate it)"
fi
echo

# --- Distinctive-string match against the reference, if provided ---
echo "### C. Distinctive-string overlap with the reference (needs a reference + judgment)"
echo
if [[ -n "$REF" && -e "$REF" && $(command -v rg) ]]; then
  rg -no '"[^"]{12,}"' "$TARGET" 2>/dev/null | sed -E 's/^[^:]+:[0-9]+://' | sort -u > /tmp/ip-cr-strings.txt || true
  if [[ -s /tmp/ip-cr-strings.txt ]]; then
    overlap="$(rg -F -f /tmp/ip-cr-strings.txt "$REF" 2>/dev/null | head -50)"
    [[ -n "$overlap" ]] && { echo "  🔴 long string literals from our code also appear in the reference:"; echo "$overlap" | sed 's/^/      /'; } || echo "  ✅ no long string literals overlap with the reference"
  else
    echo "  (no long string literals in target)"
  fi
else
  echo "  (no reference path given, or ripgrep absent — re-run with a reference-path to enable)"
fi

echo
echo "============================================================"
echo "Triage: 🔴 reference identifiers/strings/assets/structure → reimplement with OUR"
echo "prefix/text-domain (do NOT rename-and-ship). 🟡 → judgment. 🟢 → scrub."
echo "Confirm readme.txt, block.json, changelog, screenshots, banner/icon are all original."
echo "Engineering risk-reduction, NOT legal advice. STOP items → escalate to legal."
